# Site settings
title: cckkll Blog
email: 237178842@qq.com
description: > # this means to ignore newlines until "baseurl:"
  The easiest way to contact me about any computer problems or issues
  is via email. I prefer to use one email address , so you can contact me
  via 237178842@qq.com . If you have any other inquires, questions, comments,
  ideas, etc, feel free to contact me and I will do my best to respond .
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://github.com/chengyuanheng "# the base hostname & protocol for your site
twitter_username: ""
github_username:  chengyuanheng

# Build settings
markdown: kramdown