# Site settings
title: "Uncopyrighted"
description: "The quick brown fox jumps over a lazy dog"
baseurl: "/Jekyll"
url: "http://chengyuanheng.github.io/Jekyll"

# Build settings
markdown: kramdown
permalink: pretty
highlighter: pygments
paginate: 3

# Links
links:
  - title: "about"
    url: /about
  - title: "twt"
    url: http://twitter.com/alixedi
  - title: "github"
    url: http://github.com/chengyuanheng
  - title: "rss"
    url: /feed.xml
